package io.deeplay.camp.core.dto.client;

public enum ClientDtoType {
  MAKE_MOVE,
  PLACE_UNIT,
  CHANGE_PLAYER,
  START_GAME,
  CREATE_PARTY,
  JOIN_PARTY,
  SWITCH_PARTY,
  OFFER_RESTART_GAME,
  RESTART,
  GIVE_UP,
  OFFER_DRAW,
  DRAW,
  GET_PARTIES,
  DISCONNECT,
  EXIT_PARTY
}
